name: Trigger pull & rebuild

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send POST request
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d '{"action": "restart", "script":"website"}' \
        https://build.thatalex.dev/power/status?secret=${{ secrets.BUILD_SERVER }}
